---
name: "crosslink-slack-to-reamaze"
pack: "stackstorm"
description: "This rule scans the Slack RTM for mentions of re:Amaze and creates an issue notification with a permalink between Slack History and mentioned issues"
enabled: true
trigger:
  type: "slack.message"
criteria:
  trigger.text:
    type: "contains"
    pattern: "stackstorm.reamaze.com/admin/conversations"
action:
  ref: "stackstorm.crosslink_slack_to_reamaze"
  parameters:
    user: "{{trigger.user.name}}"
    text: "{{trigger.text}}"
    channel: "{{trigger.channel.name}}"
    timestamp: "{{trigger.timestamp_raw}}"
