---
name: "crosslink-slack-to-github"
pack: "stackstorm"
description: "This rule scans the Slack RTM for mentions of GitHub (PR, Issue, Gist) and creates an issue notification with a permalink between Slack History and mentioned issues"
enabled: true
trigger:
  type: "slack.message"
criteria:
  trigger.text:
    type: "matchregex"
    pattern: '.*https://github.com/(stackstorm|StackStorm|Stackstorm)/(.*)/(issues|pull)/\d+(.*)'
action:
  ref: "stackstorm.crosslink_slack_to_github"
  parameters:
    user: "{{trigger.user.name}}"
    text: "{{trigger.text}}"
    channel: "{{trigger.channel.name}}"
    timestamp: "{{trigger.timestamp_raw}}"
